/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author halamansour
 */
public class mycontactsform extends javax.swing.JFrame {

    Object jLabelusername;

    /**
     * Creates new form mycontactsform
     */
    public mycontactsform() {
        initComponents();
        UpdateCombo() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsername = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelusernameteach = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonLogin1 = new javax.swing.JButton();
        jTextFieldsubjectname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxteachers = new javax.swing.JComboBox<>();
        jTextFieldsubjectcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtongotosubject = new javax.swing.JButton();
        jButtoncreatesubject = new javax.swing.JButton();

        jTextFieldUsername.setBackground(new java.awt.Color(58, 83, 155));
        jTextFieldUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(228, 241, 254));

        jPanel1.setBackground(new java.awt.Color(58, 83, 155));

        jLabelClose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelusernameteach.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabelusernameteach.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusernameteach.setText("user :");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Welcome teacher!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelusernameteach)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelClose)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addComponent(jLabelusernameteach)
                .addContainerGap())
        );

        jButtonLogin1.setBackground(new java.awt.Color(242, 241, 239));
        jButtonLogin1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButtonLogin1.setForeground(new java.awt.Color(22, 160, 133));
        jButtonLogin1.setText("log out");
        jButtonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin1ActionPerformed(evt);
            }
        });

        jTextFieldsubjectname.setBackground(new java.awt.Color(58, 83, 155));
        jTextFieldsubjectname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextFieldsubjectname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldsubjectname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsubjectnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 139, 195));
        jLabel2.setText("Subject code :");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 139, 195));
        jLabel4.setText("Add subject name:");

        jComboBoxteachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxteachersActionPerformed(evt);
            }
        });

        jTextFieldsubjectcode.setBackground(new java.awt.Color(58, 83, 155));
        jTextFieldsubjectcode.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextFieldsubjectcode.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldsubjectcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsubjectcodeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 139, 195));
        jLabel5.setText("Select Username :");

        jButtongotosubject.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jButtongotosubject.setForeground(new java.awt.Color(22, 160, 133));
        jButtongotosubject.setText("Go to your exisiting subject ");
        jButtongotosubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongotosubjectActionPerformed(evt);
            }
        });

        jButtoncreatesubject.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jButtoncreatesubject.setForeground(new java.awt.Color(22, 160, 133));
        jButtoncreatesubject.setText("Create Subject");
        jButtoncreatesubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncreatesubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxteachers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtoncreatesubject)
                            .addComponent(jButtongotosubject)
                            .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldsubjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldsubjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldsubjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldsubjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxteachers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtoncreatesubject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtongotosubject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin1ActionPerformed

        
        loginform supF = new loginform() ; 
                 supF.setVisible(true);
                 supF.pack();
                 supF.setLocationRelativeTo(null)  ;
                 supF.setDefaultCloseOperation(loginform.EXIT_ON_CLOSE);
                 this.dispose();
    }//GEN-LAST:event_jButtonLogin1ActionPerformed
   
    // this part of the code is used to update the combo box each time a new subject is created 
    private void UpdateCombo() {
    Connection con = myConnection.getConnection() ;  
    PreparedStatement ps;
    ResultSet rs; 
    String sql = "select * from user where usertype = 'Teacher'"; 
    
    try {
    ps = con.prepareStatement(sql);
    rs = ps.executeQuery();
    JOptionPane.showMessageDialog(null, " hello ") ;
    while (rs.next()){
        jComboBoxteachers.addItem(rs.getString("username"));
    }  
    } catch (Exception e){
            
            }
    
        
    
    }
 
    
  public boolean verifsubject(){
        
       
        // if textboxes are empty 
        
        if ( jTextFieldsubjectname.getText().equals("") ||  jTextFieldsubjectcode.getText().equals(""))
        {

             JOptionPane.showMessageDialog(null, " One or more fields are missing. ");
             return false; 
        }
            return true; 
        }
          
 
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(loginform.ICONIFIED) ;
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldsubjectnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsubjectnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsubjectnameActionPerformed

    private void jTextFieldsubjectcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsubjectcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsubjectcodeActionPerformed

    private void jComboBoxteachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxteachersActionPerformed
    
    }//GEN-LAST:event_jComboBoxteachersActionPerformed
// this code verifies if a subject with that same name has already been created before 
     public boolean issubjectExist( String un ) {
       
        boolean sExist = false ; 
        Connection con = myConnection.getConnection();
       PreparedStatement ps; 
       ResultSet rs; 
       
        
        try { 
            ps = con.prepareStatement( "SELECT * FROM `subjects` WHERE `subjectname` = ? ") ;
            ps.setString(1, jTextFieldsubjectname.getText());
            
            rs = ps.executeQuery();
            
            if (rs.next()){
                
            sExist = true ;    
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
        
        
        return sExist ; 
    }
    
    
    
    
    
    private void jButtoncreatesubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncreatesubjectActionPerformed
       if (verifsubject())
        {

            Connection con = myConnection.getConnection() ;

            PreparedStatement ps;

            try {
                //ps = con.prepareStatement("INSERT INTO `user`(`fname`, `lname`, `username`, `pass`, `pic`) VALUES (?,?,?,?,?)") ;
                ps = con.prepareStatement("INSERT INTO subjects(subjectname, subjectcode, teacheruser ) VALUES (?,?,?)") ;
                ps.setString(1, jTextFieldsubjectname.getText());
                ps.setString(2, jTextFieldsubjectcode.getText());
                ps.setString(3, jComboBoxteachers.getSelectedItem().toString());

                JOptionPane.showMessageDialog( null , ps );
                if (issubjectExist(jTextFieldsubjectname.getText()) ){
                    JOptionPane.showMessageDialog( null , " Subject already exists ");
                }else {
                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog( null , " Subject created ");
                        Teachers supF = new Teachers() ;
                        supF.setVisible(true);
                        supF.pack();
                        supF.setLocationRelativeTo(null)  ;
                        supF.setDefaultCloseOperation(loginform.EXIT_ON_CLOSE);
                        supF.jLabelsubjectname.setText(jTextFieldsubjectname.getText());
                         supF.jLabeluserteach.setText(jLabelusernameteach.getText());
                        this.dispose();
                    }  else {
                        JOptionPane.showMessageDialog( null , " Something went wrong ");

                    }
                }

            } catch (Exception ex) {
                Logger.getLogger(signupform.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_jButtoncreatesubjectActionPerformed

    private void jButtongotosubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongotosubjectActionPerformed

      
    }//GEN-LAST:event_jButtongotosubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycontactsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycontactsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycontactsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycontactsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycontactsform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtoncreatesubject;
    private javax.swing.JButton jButtongotosubject;
    private javax.swing.JComboBox<String> jComboBoxteachers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelusernameteach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextField jTextFieldsubjectcode;
    private javax.swing.JTextField jTextFieldsubjectname;
    // End of variables declaration//GEN-END:variables
}
