
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author halamansour
 */
public class Students extends javax.swing.JFrame {
public String teacheruser = null ; 
public byte[] img; 
    /**
     * Creates new form Students
     */
    public Students() {
       // Show_subjects_inTable();
        initComponents();
           jp3.setVisible(false);
          
           jp1.setVisible(false);
           jp4.setVisible(false);
           jTextFieldteacheruser.setVisible(false);
           jTextFieldtasksubject.setVisible(false);
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelPicture = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jpmain = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jp3 = new javax.swing.JPanel();
        jTextFieldcodesubj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonaddsubject = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jp4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablestudenttasks = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldtasktitle = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextFieldanswer = new javax.swing.JTextField();
        jLabelPicture1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonsubmittask = new javax.swing.JButton();
        jTextFieldtasksubject = new javax.swing.JTextField();
        jTextFieldteacheruser = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelusernamestudent = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonLogin1 = new javax.swing.JButton();
        jLabelpicstudent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelPicture.setBackground(new java.awt.Color(58, 83, 155));
        jLabelPicture.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(222, 247, 255));

        jpmain.setBackground(new java.awt.Color(204, 204, 204));
        jpmain.setLayout(new java.awt.CardLayout());

        jp1.setBackground(new java.awt.Color(255, 255, 153));
        jp1.setForeground(new java.awt.Color(252, 234, 234));
        jp1.setLayout(new java.awt.CardLayout());

        jp3.setBackground(new java.awt.Color(204, 204, 255));
        jp3.setMaximumSize(new java.awt.Dimension(800, 800));
        jp3.setPreferredSize(new java.awt.Dimension(800, 1400));
        jp3.setLayout(null);

        jTextFieldcodesubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcodesubjActionPerformed(evt);
            }
        });
        jp3.add(jTextFieldcodesubj);
        jTextFieldcodesubj.setBounds(281, 200, 379, 51);

        jLabel7.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Join a new subject ");
        jp3.add(jLabel7);
        jLabel7.setBounds(281, 122, 367, 43);

        jButtonaddsubject.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButtonaddsubject.setForeground(new java.awt.Color(0, 153, 51));
        jButtonaddsubject.setText("Add");
        jButtonaddsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddsubjectActionPerformed(evt);
            }
        });
        jp3.add(jButtonaddsubject);
        jButtonaddsubject.setBounds(400, 290, 125, 50);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Enter the code for your subject :");
        jp3.add(jLabel8);
        jLabel8.setBounds(60, 220, 217, 17);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jp3.add(jSeparator1);
        jSeparator1.setBounds(672, 209, 186, 0);

        jp1.add(jp3, "card4");

        jpmain.add(jp1, "card4");

        jp4.setBackground(new java.awt.Color(204, 235, 231));

        jTablestudenttasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Task title ", "Task"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablestudenttasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablestudenttasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablestudenttasks);
        if (jTablestudenttasks.getColumnModel().getColumnCount() > 0) {
            jTablestudenttasks.getColumnModel().getColumn(2).setMinWidth(0);
            jTablestudenttasks.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTablestudenttasks.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jLabel10.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel10.setText("Task title : ");

        jLabel11.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel11.setText("Task :");

        jLabel12.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel12.setText("Answer : ");

        jLabel13.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel13.setText("Image : ");

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel15.setText("Answer Tasks");

        jTextFieldtasktitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtasktitleActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextFieldanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldanswerActionPerformed(evt);
            }
        });

        jLabelPicture1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPicture1.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonsubmittask.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonsubmittask.setForeground(new java.awt.Color(0, 204, 0));
        jButtonsubmittask.setText("Submit ");
        jButtonsubmittask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmittaskActionPerformed(evt);
            }
        });

        jTextFieldtasksubject.setText("jTextField2");
        jTextFieldtasksubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtasksubjectActionPerformed(evt);
            }
        });

        jTextFieldteacheruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacheruserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addComponent(jLabel13)))
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldtasksubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldteacheruser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldtasktitle)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonsubmittask))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldtasksubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldteacheruser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtasktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(128, 128, 128))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsubmittask, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jpmain.add(jp4, "card4");

        jPanel1.setBackground(new java.awt.Color(0, 155, 140));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N

        jLabelClose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelusernamestudent.setBackground(new java.awt.Color(204, 255, 255));
        jLabelusernamestudent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabelusernamestudent.setForeground(new java.awt.Color(204, 255, 255));
        jLabelusernamestudent.setText("user :");

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Welcome student !");

        jButtonLogin1.setBackground(new java.awt.Color(242, 241, 239));
        jButtonLogin1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButtonLogin1.setForeground(new java.awt.Color(22, 160, 133));
        jButtonLogin1.setText("Log out");
        jButtonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelpicstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269)
                .addComponent(jLabelusernamestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(908, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelusernamestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelpicstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(16, 16, 16)))
        );

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 39, 56));
        jLabel4.setText("Student Menu");

        tab2.setBackground(new java.awt.Color(255, 255, 255));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Answer tasks");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tab3.setBackground(new java.awt.Color(255, 255, 255));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Join new subject");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        jLabel1.setText("(6 Characters only)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(417, 417, 417))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(jpmain, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addGap(175, 175, 175)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jpmain, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGap(86, 86, 86)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin1ActionPerformed
        loginform supF = new loginform() ;
        supF.setVisible(true);
        supF.pack();
        supF.setLocationRelativeTo(null)  ;
        supF.setDefaultCloseOperation(loginform.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonLogin1ActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(loginform.ICONIFIED) ;
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp4.setVisible(true);
        jp3.setVisible(false);
        jp1.setVisible(false);
        
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp4.setVisible(false);
        jp3.setVisible(true);
        jp1.setVisible(false);
        
    }//GEN-LAST:event_tab3MouseClicked

    private void jButtonaddsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddsubjectActionPerformed
       
        // this button allows studnets to enter their classes 
        Connection con = myConnection.getConnection(); 
        Statement st ; 
        ResultSet rs;   
        PreparedStatement ps; 
        
    
       
            try {
              // this code checks from the database whether the student has enetered the correct code for their subject and checks their student id before entering the admiting into the class
                ps = con.prepareStatement( "INSERT INTO student_subject (idstudent, subjectcode) select (Select id from user where username ='"+jLabelusernamestudent.getText()+"' ) as idstudent, (select subjectcode from subjects where subjectcode='"+jTextFieldcodesubj.getText()+"') as subjectcode" );
               // JOptionPane.showMessageDialog(null, query);
                
                if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog( null , " You have joined this class ");
                }  else {
                        JOptionPane.showMessageDialog( null , " Incorrect subject code ");
                }
                
                
                
          } catch (SQLException ex) {
                Logger.getLogger(Students.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog( null , " Incorrect subject code ");
          }
        
        
    }//GEN-LAST:event_jButtonaddsubjectActionPerformed

    
    // this code selects the tasks according to the subjects that the student has entered, and holds them in an array 
       public ArrayList<task> gettaskslist()
    {
        ArrayList<task> stList = new ArrayList<task> ();
        Connection con = myConnection.getConnection();  
        String query = "SELECT tasks.id, tasks.tasktitle, tasks.task, tasks.task_subject , tasks.teacher , "
                + "tasks.taskpic FROM tasks, user, student_subject, subjects where user.username ='"+jLabelusernamestudent.getText()+"'"
        + " and \n" +
        "user.id=student_subject.idstudent and \n" +
        "student_subject.subjectcode = subjects.subjectcode and\n" +
        "tasks.task_subject=subjects.subjectname " ;
               
        Statement st ; 
        ResultSet rs; 
            try {
                st = con.createStatement();
                rs = st.executeQuery(query);  
                task Task;
            while(rs.next()) {
              
                img = rs.getBytes(6);
                jLabelPicture1.setIcon(new MyFunc().resizePic(null, img, jLabelPicture1.getWidth() , jLabelPicture1.getHeight()));
               Task = new task( rs.getString("tasktitle"), rs.getString("task") , rs.getInt("id") , 
                       rs.getString("task_subject") ,rs.getString("teacher") ,rs.getBytes("taskpic")  ) ;
                
              stList.add(Task);
            
          }
              
        } catch (Exception e){  
            e.printStackTrace();
        }
        return stList;
    } 
    
       
       // the previous array is displayed in a table for the students to see the tasks of their subjects 
        public void Show_tasks_inTable() {
        
        
        ArrayList<task> list = gettaskslist();
        DefaultTableModel model = (DefaultTableModel)jTablestudenttasks.getModel();
        Object row [] = new Object [4];
        for(int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTask_subject();
            row[1] = list.get(i).getTasktitle();
            row[2] = list.get(i).getTask();
            row[3] = list.get(i).getTaskpic();
            
            
            
            model.addRow(row);
        }
        
    }
       
       
       public void executeQuery(String query, String message) {
        Connection con = myConnection.getConnection(); 
        Statement st; 
        try {
           st = con.createStatement();
           if ((st.executeUpdate(query)) == 1 ){
               
               // refresh the table 
               DefaultTableModel model = (DefaultTableModel)jTablestudenttasks.getModel();
               model.setRowCount(0);
               Show_tasks_inTable() ;
        
               
               
               JOptionPane.showMessageDialog(null,"Data "+message+" Successfully" );
           } else {
               JOptionPane.showMessageDialog(null,"Data Not "+message);
           }    
        }catch (Exception ex) {
            ex.printStackTrace();
        }
    }  
        
        
        
  
    
    private void jTextFieldcodesubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcodesubjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcodesubjActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Show_tasks_inTable() ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextFieldtasktitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtasktitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtasktitleActionPerformed

    private void jTablestudenttasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablestudenttasksMouseClicked
        //display selected row from table in Jtextfield 
        
        jTextFieldtasktitle.setEditable(false);
        jTextField3.setEditable(false);
        
        
       int i = jTablestudenttasks.getSelectedRow();
        TableModel model = jTablestudenttasks.getModel();
        jTextFieldtasksubject.setText(model.getValueAt(i,0).toString());
        jTextFieldtasktitle.setText(model.getValueAt(i,1).toString());
        jTextField3.setText(model.getValueAt(i,2).toString());
        jLabelPicture1.setText(model.getValueAt(i,3).toString());
    //   jLabelPicture1.setIcon(resizePic(model.getValueAt(i,3).toString())));
    }//GEN-LAST:event_jTablestudenttasksMouseClicked

    private void jButtonsubmittaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmittaskActionPerformed
      
        // the following lines of code submit the answers that the student has entered 
            Connection con = myConnection.getConnection() ;

            PreparedStatement ps;
            ResultSet rs; 
         
                try { 
              
                ps = con.prepareStatement("SELECT `teacheruser` FROM `subjects` WHERE `subjectname` = '"+jTextFieldtasksubject.getText()+"' ") ; 
                rs = ps.executeQuery();
                
                 if (rs.next()){
                     teacheruser =  rs.getString(1);
                 
 
                 }
        }catch (Exception ex) {
            ex.printStackTrace();
        }
           try {
               
       // the student's answers are put into a table on the database which will later be displayed to the teachers         
        
               ps = con.prepareStatement("INSERT INTO student_answers(teacher_name,subject,studentname,answer) VALUES (?,?,?,?)") ;
               ps.setString(1, teacheruser );
               ps.setString(2,jTextFieldtasksubject.getText());
               ps.setString(3, jLabelusernamestudent.getText());
               ps.setString(4, jTextFieldanswer.getText());
          
               
             if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog( null , " Task submitted ");
             }
             }catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButtonsubmittaskActionPerformed

    private void jTextFieldteacheruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacheruserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacheruserActionPerformed

    private void jTextFieldtasksubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtasksubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtasksubjectActionPerformed

    private void jTextFieldanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldanswerActionPerformed
 
       public ImageIcon resizePic(String picPath) {
        
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance( jLabelPicture1.getWidth() ,jLabelPicture1.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon myPicture  = new ImageIcon(img)  ;    
        return myPicture ; 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
        }
    
    
    // select tasktitle from tasks, subjects, student_subject where subjects.subjectname='chem' and student_subject.idsetudent=3

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtonaddsubject;
    private javax.swing.JButton jButtonsubmittask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelPicture1;
    public javax.swing.JLabel jLabelpicstudent;
    public javax.swing.JLabel jLabelusernamestudent;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablestudenttasks;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldanswer;
    private javax.swing.JTextField jTextFieldcodesubj;
    private javax.swing.JTextField jTextFieldtasksubject;
    private javax.swing.JTextField jTextFieldtasktitle;
    private javax.swing.JTextField jTextFieldteacheruser;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jpmain;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    // End of variables declaration//GEN-END:variables
}
